### ISSUE TITLE
Error: GitHub: 2FA required, but options.on2fa is not a function

### ISSUE THREAD

**Issue by mm-gmbd** [NasibMansour/imp-central-impt#28]
If the Github account described in the auth file requires 2FA and a Builder GH include is specified, then the build will fail:

```bash
Error: { Deprecation: [@octokit/rest] octokit.authenticate() is deprecated. Use "auth" constructor option instead.
    at authenticate (/users/me/.nvm/versions/node/v10.15.2/lib/node_modules/imp-central-impt/node_modules/@octokit/rest/plugins/authentication-deprecated/authenticate.js:9:44)
    at Function.fetch (/users/me/.nvm/versions/node/v10.15.2/lib/node_modules/imp-central-impt/node_modules/Builder/src/Readers/GithubReader.js:191:15)
    at Object.<anonymous> (/users/me/.nvm/versions/node/v10.15.2/lib/node_modules/imp-central-impt/node_modules/Builder/src/Readers/GithubReader.js:294:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19) name: 'Deprecation' }
Failed to get source "github:electricimp/MessageManager/MessageManager.lib.nut@2.2.0" from GitHub: 2FA required, but options.on2fa is not a function. See https://github.com/octokit/rest.js#authentication (src/EMCB.agent.nut:53)
IMPT COMMAND FAILS
```

**Comment by mm-gmbd** [comment]
NVM -- using a personal access token as the `githubToken` worked fine. Closing.
